// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'C:/Users/Pathways Technology/Desktop/CBC/carbon_credit/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from 'C:/Users/Pathways Technology/Desktop/CBC/carbon_credit/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from 'C:/Users/Pathways Technology/Desktop/CBC/carbon_credit/node_modules/@ant-design/icons/es/icons/FormOutlined';
export default { SmileOutlined, DashboardOutlined, FormOutlined };
