// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/isutsa_/Documents/carbon-credit/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from '/home/isutsa_/Documents/carbon-credit/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from '/home/isutsa_/Documents/carbon-credit/node_modules/@ant-design/icons/es/icons/FormOutlined';
export default { SmileOutlined, DashboardOutlined, FormOutlined };
